CREATE TABLE CHEQUETERCEIROTITULOGERADO
(
	IDCHEQUETERCEIROTITULOGERADO NUMERIC(18) NOT NULL,
	IDCHEQUETERCEIRO     NUMERIC(18) NOT NULL,
	IDTITULO             NUMERIC(18) NOT NULL 
);

CREATE SEQUENCE IDCHEQUETERCEIROTITULOGERADO NOCACHE;

ALTER TABLE CHEQUETERCEIROTITULOGERADO
	ADD CONSTRAINT  XPKCHEQUETERCEIROTITULOGERADO PRIMARY KEY (IDCHEQUETERCEIROTITULOGERADO);

	
CREATE TABLE CHEQUETERCEIROTITULOORIG
(
	IDCHEQUETERCEIROTITULOORIG NUMERIC(18) NOT NULL ,
	IDCHEQUETERCEIRO     NUMERIC(18) NOT NULL ,
	IDTITULO             NUMERIC(18) NOT NULL 
);

CREATE SEQUENCE IDCHEQUETERCEIROTITULOORIG NOCACHE;

ALTER TABLE CHEQUETERCEIROTITULOORIG
	ADD CONSTRAINT  XPKCHEQUETERCEIROTITULOORIG PRIMARY KEY (IDCHEQUETERCEIROTITULOORIG);
	
	
CREATE TABLE TIPOMOVIMENTOCHEQUE
(
	IDTIPOMOVIMENTOCHEQUE NUMERIC(18) NOT NULL ,
	CODIGO               NUMERIC(6) NOT NULL ,
	DESCRICAO            VARCHAR2(80) NOT NULL 
);

ALTER TABLE TIPOMOVIMENTOCHEQUE
	ADD CONSTRAINT  XPKTIPOMOVIMENTOCHEQUE PRIMARY KEY (IDTIPOMOVIMENTOCHEQUE);	
	
	
CREATE TABLE CHEQUETERCEIROMOVIMENTACAO
(
	IDCHEQUETERCEIROMOVIMENTACAO NUMERIC(18) NOT NULL,
	IDTIPOMOVIMENTOCHEQUE NUMERIC(18) NOT NULL,
	OBSERVACAO           VARCHAR2(400) NULL,
	IDPARCEIROPORTADOR   NUMERIC(18) NULL,
	IDFLAGSTATUSCHEQUE   NUMERIC(18) NOT NULL,
	IDUSUARIO            NUMERIC(18) NOT NULL 
);

CREATE SEQUENCE IDCHEQUETERCEIROMOVIMENTACAO NOCACHE;

ALTER TABLE CHEQUETERCEIROMOVIMENTACAO
	ADD CONSTRAINT  XPKCHEQUETERCEIROMOVIMENTACAO PRIMARY KEY (IDCHEQUETERCEIROMOVIMENTACAO);

	
CREATE  INDEX XIF1CHEQUETERCEIROTITULOGERADO ON CHEQUETERCEIROTITULOGERADO(IDCHEQUETERCEIRO   ASC);

CREATE  INDEX XIF2CHEQUETERCEIROTITULOGERADO ON CHEQUETERCEIROTITULOGERADO(IDTITULO   ASC);

ALTER TABLE CHEQUETERCEIROTITULOGERADO
	ADD CONSTRAINT FKCHEQUETERTOCHEQTERTITGERADO FOREIGN KEY (IDCHEQUETERCEIRO) REFERENCES CHEQUETERCEIRO (IDCHEQUETERCEIRO);

ALTER TABLE CHEQUETERCEIROTITULOGERADO
	ADD CONSTRAINT FKTITULOTOCHEQTERTITGERADO FOREIGN KEY (IDTITULO) REFERENCES TITULO (IDTITULO);


CREATE  INDEX XIF1CHEQUETERCEIROTITULOORIG ON CHEQUETERCEIROTITULOORIG(IDCHEQUETERCEIRO   ASC);

CREATE  INDEX XIF2CHEQUETERCEIROTITULOORIG ON CHEQUETERCEIROTITULOORIG(IDTITULO   ASC);


ALTER TABLE CHEQUETERCEIROTITULOORIG
	ADD CONSTRAINT FKCHEQTERCTOCHEQTERCTITORIG 
	FOREIGN KEY (IDCHEQUETERCEIRO) REFERENCES CHEQUETERCEIRO (IDCHEQUETERCEIRO)  DEFERRABLE  INITIALLY DEFERRED;

ALTER TABLE CHEQUETERCEIROTITULOORIG
	ADD CONSTRAINT FKTITULOTOCHEQUETERCEIROTITORI 
	FOREIGN KEY (IDTITULO) REFERENCES TITULO (IDTITULO)  DEFERRABLE  INITIALLY DEFERRED;


CREATE  INDEX XIF1CHEQUETERCEIROMOVIMENTACAO ON CHEQUETERCEIROMOVIMENTACAO(IDTIPOMOVIMENTOCHEQUE   ASC);

CREATE  INDEX XIF2CHEQUETERCEIROMOVIMENTACAO ON CHEQUETERCEIROMOVIMENTACAO(IDPARCEIROPORTADOR   ASC);

CREATE  INDEX XIF3CHEQUETERCEIROMOVIMENTACAO ON CHEQUETERCEIROMOVIMENTACAO(IDFLAGSTATUSCHEQUE   ASC);

CREATE  INDEX XIF4CHEQUETERCEIROMOVIMENTACAO ON CHEQUETERCEIROMOVIMENTACAO(IDUSUARIO   ASC);


ALTER TABLE CHEQUETERCEIROMOVIMENTACAO
	ADD CONSTRAINT FKTIPOMOVCHEQTOCHEQTERMOV 
	FOREIGN KEY (IDTIPOMOVIMENTOCHEQUE) REFERENCES TIPOMOVIMENTOCHEQUE (IDTIPOMOVIMENTOCHEQUE)  DEFERRABLE  INITIALLY DEFERRED;

ALTER TABLE CHEQUETERCEIROMOVIMENTACAO
	ADD CONSTRAINT FKPARCEIROPORTADORTOCHETERMOVT 
	FOREIGN KEY (IDPARCEIROPORTADOR) REFERENCES PARCEIRO (IDPARCEIRO)  DEFERRABLE  INITIALLY DEFERRED;

ALTER TABLE CHEQUETERCEIROMOVIMENTACAO
	ADD CONSTRAINT FKFLAGSTATUSCHTOCHEQTERMOVTO 
	FOREIGN KEY (IDFLAGSTATUSCHEQUE) REFERENCES FLAG (IDFLAG)  DEFERRABLE  INITIALLY DEFERRED;

ALTER TABLE CHEQUETERCEIROMOVIMENTACAO
	ADD CONSTRAINT FKUSUARIOTOCHEQTERCEIROMOVTO 
	FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (IDUSUARIO)  DEFERRABLE  INITIALLY DEFERRED;
